# do not run docker-compose directly, see README.md

# NB: this is only used for local development
# see Dockerfile for deployed version

django:
  build: .
  command: make start
  volumes:
    # - .:/app
    - /tmp/pip_download_cache:/root/.cache/pip
  ports:
    - "8002:8002"
  environment:
    ENV: local
    DEBUG: "True"
    DJANGO_SECRET_KEY: CHANGE_ME
    API_URL: http://${HOST_MACHINE_IP}:8000
